---
title: Chosen Wines
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: Pages
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: The Chosen Wines blog!
baseurl:
url:
gems:
- jekyll-paginate-v2
# Pagination Settings
pagination:
  enabled: true
  per_page: 8
  permalink: '/archive/:num/'
  title: ' Archive of reviews - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true